### ISSUE TITLE
Incomplete code lists?

### ISSUE THREAD

**Issue by reidmporter** [datasets/dac-crs-codes#39]
I realize the point of this project is NOT to make more work for yourself, but any idea why the codelists you based these files on (taken from here I assume: http://www.oecd.org/dac/stats/dacandcrscodelists.htm) do not match with the codes found elsewhere in the bulk downloads (https://stats.oecd.org/DownloadFiles.aspx?DatasetCode=CRS1) or in the OECD.stat tool (https://stats.oecd.org/Index.aspx?DataSetCode=CRS1#) for instance:

ODA: codelist says 10, OECD.stat says 100, and codelist doesn't contain the 11, 13, 19 breakdown, but OECD.stat does?

**Comment by andylolz** [comment]
> taken from here I assume

There is no need to assume! [It’s in the README](https://github.com/datasets/dac-crs-codes/blob/d744859b77d9de4f98fa07c4ee0f7c2cedcca7f0/README.md):

> Here you can find these codes republished in a machine readable format. They’re fetched from an excel file [available on the OECD website](http://www.oecd.org/dac/stats/dacandcrscodelists.htm).

:rocket: :rocket: :rocket:

> ODA: codelist says 10, OECD.stat says 100, and codelist doesn't contain the 11, 13, 19 breakdown, but OECD.stat does?

You’re talking about type of flow? I see what you mean, yes – good point! So according to OECD.stat:

11: ODA Grants
13: ODA Loans
19: Equity Investment
14: Other Official Flows (non Export Credit)

I’m afraid I don’t know the answer… I suspect it is a historical artefact, but since I’ve only been keeping track for a few months, I’m afraid I don’t have that information. I do know that “OOF” was previously code 20, and was removed in fc3be017.

Other codelists nerds such as @markbrough or @yohannaloucheur may well know better.

**Comment by YohannaLoucheur** [comment]
No idea, sorry. I don't follow OECD CRS codelists that closely.

Seems to me this is a question best answered by the DAC secretariat, no? Reid, perhaps you could ask Valérie Thielemans?

**Comment by andylolz** [comment]
Good point – Valérie attended the miniTAG, right? Yeah, I’m sure she’d be able to shed some light.

**Comment by andylolz** [comment]
Going to close this issue, since I don’t think it’s a problem with these codelists… (Although it’s a bit concerning that there appears to be a discrepancy.)
